controllers:
    resource: ../src/Controller/
    type: annotation
    prefix: '' # Esto agregará el prefijo a todas las rutas definidas en tus controladores

homepage:
    resource: App\Controller\HomepageController
    type: annotation

cambiar_idioma:
    path: /idioma/{_locale}
    controller: App\Controller\IdiomaController::cambiarIdioma
    methods: ['GET', 'POST']
    requirements:
        _locale: en|es

paypal_create_payment:
    path: '/paypal/create-payment'
    controller: 'App\Controller\PaypalController::createPayment'

paypal_execute_payment:
    path: '/paypal/execute-payment'
    controller: 'App\Controller\PaypalController::executePayment'

paypal_cancel_payment:
    path: '/paypal/cancel-payment'
    controller: 'App\Controller\PaypalController::cancelPayment'

paypal_success_payment:
    path: '/paypal/success-payment'
    controller: 'App\Controller\PaypalController::successPayment'
    methods: ['GET']

# config/routes.yaml
contact_form_submit:
    path: '/submit_contact_form'
    controller: 'App\Controller\ContactController::submitForm'
