controllers:
    resource: ../src/Controller/
    type: annotation
    prefix: '' # Esto agregará el prefijo a todas las rutas definidas en tus controladores

homepage:
    resource: App\Controller\HomepageController
    type: annotation

cambiar_idioma:
    path: /idioma/{_locale}
    controller: App\Controller\IdiomaController::cambiarIdioma
    methods: ['GET', 'POST']
    requirements:
        _locale: en|es
